### PR TITLE
45 Fixing current adc

### PR DESCRIPTION
**Pull request by stevegtaylor**
---
name: Stephen Taylor
about: Implementing Current Readings
title: Junior Specialist 
labels: ''
assignees: 
reviewers: 'jmadden173'
---

**Name/Affiliation/Title**
Stephen Taylor/UCSC/JS

**Purpose of the PR**
Fixed the timing issues with HAL that prevented current readings. Cleaned up libraries to match style guide.

**Development Environment**
Windows, SPS 2.2

**Test Procedure**
Run the unit test, this should test whether the ADC can even function. Then hook the SPS current and voltage ports and run the 'example_adc' environment to check for reasonable values.

**Additional Context**
N/A

### CODE REVIEW

**Comment by jmadden173** [comment]
I'm confused, is the PR fixing the current measurements? Or adding calibration files? How do I test it? The build is also failing. Conflicts need to be fixed as well.

**Comment by stevegtaylor** [comment]
`.pio\build\stm32\src\lora_app.o: In function `LoRaWAN_Init':
lora_app.c:(.text.LoRaWAN_Init+0xc4): undefined reference to `TimeSync'
lora_app.c:(.text.LoRaWAN_Init+0xc8): undefined reference to `OnTimeSync'`

The build failing is due to the functions you didn't include in `user code`, this should be resolved upon merge.

**Comment by stevegtaylor** [comment]
Closes #45

**Review by jmadden173 — APPROVED** [review]
Looks good to me. I couldn't test since I think that I fried the ADC chip. The SDI-12 test gets blocked, not really worry about it. Adding it to CI unit test issue (#59)

**Pull request merged**
