### PR TITLE
Hotfix: Restored clock configuration

### PR DESCRIPTION
**Pull request by jmadden173**
**Name/Affiliation/Title**
John

**Purpose of the PR**
Fix `main` getting stuck on a disable irq function

**Development Environment**
`Linux spruce 6.8.2-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000 x86_64 GNU/Linux`
PlatformIO Core, version 6.1.7
Used ST-Link V3 MINIE
Used CubeMX version `10.0`

**Test Procedure**
Run `main` and see if code gets past printing the LoRa UUIDs.

**Additional Context**
Also enabled `DEBUGGER_ENABLED` in `sys_conf.h`.
Some reason `tim.h/.c` got new line endings hence rewrite.

@stevegtaylor Feel free to change the merge branches so that you  merge into the issue branch

### CODE REVIEW

**Comment by stevegtaylor** [comment]
tested and succeeded. not sure how to change merge branches.

**Review by stevegtaylor — APPROVED** [review]
Test passed

**Comment by stevegtaylor** [comment]
#80 only changes 6 files, the only file in common changed with this branch is `main.c` and I don't foresee it causing merge conflicts. I think I should be able to merge #81 and than #80 without issue.

#80  in this case will adjust the ADC, add unit testing for main, and adjust the calibration file for the ADC

@jmadden173 please take a look and tell me if you agree

**Comment by jmadden173** [comment]
Seems reasonable to me. If you make the PR for #80, I'll approve it. After you merge one of the branches you should rebase/merge into the other branch and check if everything works before merging the other one.

John

Sent from Proton Mail Android

-------- Original Message --------

**Pull request merged**
